export const LOADING = "LOADING";
export const HANDLE_DIALOG_STATE = "HANDLE_DIALOG_STATE";
export const SNACKBAR_STATE = "SNACKBAR_STATE";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const USER_LOADED = "USER_LOADED";

export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_RESULTS = "SET_RESULTS";
export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SET_CURRENT_CHOICE = "SET_CURRENT_CHOICE";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
